apiVersion: v1
kind: Namespace
metadata:
  name: guacamole
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-pvc
  namespace: guacamole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
# ============================================================
#  Guacamole - All-in-one (jwetzell/guacamole for ARM64)
#  Bundles guacd + guacamole client + built-in DB
#  Official Apache images do NOT support ARM64/aarch64
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: guacamole
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
      - name: guacamole
        image: jwetzell/guacamole:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: guac-data
          mountPath: /config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 15
          failureThreshold: 5
      volumes:
      - name: guac-data
        persistentVolumeClaim:
          claimName: guacamole-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole-service
  namespace: guacamole
spec:
  selector:
    app: guacamole
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guacamole-ingress
  namespace: guacamole
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: guacamole.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guacamole-service
            port:
              number: 80
