apiVersion: v1
kind: Namespace
metadata:
  name: aiostreams
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiostreams
  namespace: aiostreams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiostreams
  template:
    metadata:
      labels:
        app: aiostreams
    spec:
      containers:
      - name: aiostreams
        image: viren070/aiostreams:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=512"
        envFrom:
        - secretRef:
            name: aiostreams-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "768Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: aiostreams-service
  namespace: aiostreams
spec:
  selector:
    app: aiostreams
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aiostreams-ingress
  namespace: aiostreams
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: aiostreams.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aiostreams-service
            port:
              number: 80
