# AdGuard Home - network-wide DNS ad/tracker blocker
# Runs as a K8s deployment with a Longhorn PVC for config persistence
# Uses NodePort on port 53 (DNS) so all devices on the network can use it
# Web UI available at http://adguard.local
---
apiVersion: v1
kind: Namespace
metadata:
  name: adguard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work-pvc
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-conf-pvc
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  namespace: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-home
  strategy:
    type: Recreate    # PVC is ReadWriteOnce - can't have two pods
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      automountServiceAccountToken: false
      containers:
        - name: adguard-home
          image: adguard/adguardhome:v0.107.55
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: web
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: work
              mountPath: /opt/adguardhome/work
            - name: conf
              mountPath: /opt/adguardhome/conf
          resources:
            requests:
              memory: "48Mi"
              cpu: "25m"
              ephemeral-storage: "64Mi"
            limits:
              memory: "128Mi"
              cpu: "200m"
              ephemeral-storage: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 30
      volumes:
        - name: work
          persistentVolumeClaim:
            claimName: adguard-work-pvc
        - name: conf
          persistentVolumeClaim:
            claimName: adguard-conf-pvc
---
# DNS service - NodePort so every device on the LAN can use <NODE_IP>:53
apiVersion: v1
kind: Service
metadata:
  name: adguard-dns-tcp
  namespace: adguard
spec:
  type: NodePort
  selector:
    app: adguard-home
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
      nodePort: 30053
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-dns-udp
  namespace: adguard
spec:
  type: NodePort
  selector:
    app: adguard-home
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
      nodePort: 30053
---
# Web UI service - ClusterIP, exposed via Traefik ingress
apiVersion: v1
kind: Service
metadata:
  name: adguard-web-service
  namespace: adguard
spec:
  selector:
    app: adguard-home
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-ingress
  namespace: adguard
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: adguard.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adguard-web-service
                port:
                  number: 80
